# Generated by Django 5.2.6 on 2025-10-13 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
        ('game', '0003_turn_move'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.lobby'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lobby', '-sent_at'], name='chat_messag_lobby_i_96d6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', '-sent_at'], name='chat_messag_sender__ba5b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='chat_messag_sent_at_67fe48_idx'),
        ),
    ]
