# Generated by Django 5.2.6 on 2025-11-15 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatparticipant_user'),
        ('game', '0003_turn_move'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_lobby_i_96d6b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__ba5b4a_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_lobby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='game.lobby'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'chat', '-sent_at'], name='chat_messag_sender__19bd32_idx'),
        ),
    ]
