# Generated by Django 5.2.6 on 2025-10-13 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='game',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='player',
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='cardrank',
            options={'ordering': ['value'], 'verbose_name': 'Card Rank', 'verbose_name_plural': 'Card Ranks'},
        ),
        migrations.AlterModelOptions(
            name='cardsuit',
            options={'ordering': ['name'], 'verbose_name': 'Card Suit', 'verbose_name_plural': 'Card Suits'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-started_at'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamedeck',
            options={'ordering': ['position'], 'verbose_name': 'Game Deck Card', 'verbose_name_plural': 'Game Deck Cards'},
        ),
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['seat_position'], 'verbose_name': 'Game Player', 'verbose_name_plural': 'Game Players'},
        ),
        migrations.AlterModelOptions(
            name='lobby',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lobby', 'verbose_name_plural': 'Lobbies'},
        ),
        migrations.AlterModelOptions(
            name='lobbyplayer',
            options={'ordering': ['lobby', 'user__username'], 'verbose_name': 'Lobby Player', 'verbose_name_plural': 'Lobby Players'},
        ),
        migrations.AlterModelOptions(
            name='lobbysettings',
            options={'verbose_name': 'Lobby Settings', 'verbose_name_plural': 'Lobby Settings'},
        ),
        migrations.AlterModelOptions(
            name='playerhand',
            options={'ordering': ['order_in_hand'], 'verbose_name': 'Player Hand Card', 'verbose_name_plural': 'Player Hand Cards'},
        ),
        migrations.AlterModelOptions(
            name='specialcard',
            options={'ordering': ['name'], 'verbose_name': 'Special Card', 'verbose_name_plural': 'Special Cards'},
        ),
        migrations.AlterModelOptions(
            name='specialruleset',
            options={'ordering': ['name'], 'verbose_name': 'Special Rule Set', 'verbose_name_plural': 'Special Rule Sets'},
        ),
        migrations.AlterModelOptions(
            name='specialrulesetcard',
            options={'ordering': ['rule_set__name', 'card__name'], 'verbose_name': 'Special Rule Set Card', 'verbose_name_plural': 'Special Rule Set Cards'},
        ),
        migrations.AlterModelOptions(
            name='tablecard',
            options={'ordering': ['id'], 'verbose_name': 'Table Card', 'verbose_name_plural': 'Table Cards'},
        ),
        migrations.AddField(
            model_name='specialrulesetcard',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='effect_type',
            field=models.CharField(choices=[('skip', 'Skip Turn'), ('reverse', 'Reverse Order'), ('draw', 'Draw Cards'), ('custom', 'Custom Effect')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='effect_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='specialruleset',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='specialruleset',
            name='min_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='specialruleset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('suit', 'rank', 'special_card')},
        ),
        migrations.AlterUniqueTogether(
            name='gamedeck',
            unique_together={('game', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='lobbyplayer',
            unique_together={('lobby', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='playerhand',
            unique_together={('game', 'player', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='specialrulesetcard',
            unique_together={('rule_set', 'card')},
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Turn',
        ),
    ]
